<?php

namespace Database\Seeders;

use App\Models\Link;
use Illuminate\Database\Seeder;

class LinkSeeder extends Seeder
{
    public function run(): void
    {
        $links = [
            //Official Files
            [
                'title' => 'PUP Student Handbook 2019 Revised Edition',
                'description' => 'Outlines the policies that govern student rights, responsibilities, conduct, and academic life throughout the University System.',
                'url' => 'https://drive.google.com/file/d/0B1BuDAuN0r8SX1BWX2NSN3FURzg/view?usp=sharing&resourcekey=0-oi8lUy9PCFysh0FDyL5ipw',
                'type' => 'file',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Forms for Students',
                'description' => 'Official repository of downloadable forms for PUP Students.',
                'url' => 'https://www.pup.edu.ph/downloads/students',
                'type' => 'file',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => "PUP Citizen's Charter",
                'description' => 'Outlines the step-by-step process, requirements, and service timelines for the university services to the community.',
                'url' => 'https://drive.google.com/file/d/0B1BuDAuN0r8SbmFEU1RJUDFYU1E/view?usp=sharing&resourcekey=0-ntyYkBAnyIFKdRJWhiKEcw',
                'type' => 'file',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => "PUP Graduate School and Thesis/Dissertation Forms",
                'description' => 'Official repository of downloadable forms for PUP Graduate School students and students who are working on their thesis and dissertation.',
                'url' => 'https://www.pup.edu.ph/gs/forms',
                'type' => 'file',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            //Official Websites
            [
                'title' => 'Official PUP Website',
                'description' => 'The official website and portal of the Polytechnic University of the Philippines, providing the online community with access to university information.',
                'url' => 'https://www.pup.edu.ph/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Smart Interactive Technical Assistant (PUP SINTA)',
                'description' => 'The official PUP website that serves as an AI-powered helpdesk, assisting with inquiries about student services, technical issues, and administrative concerns.',
                'url' => 'https://pupsinta.freshservice.com/support/home',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP University Library',
                'description' => 'The official online catalog of the PUP University Library where users can search for books, theses, journals, and other academic resources available in the library system.',
                'url' => 'https://ils.pup.edu.ph/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP iApply',
                'description' => 'The official online portal that allows applicants to register for college admission evaluations and entrance exams.',
                'url' => 'https://iapply.pup.edu.ph/signin',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Student Information System (PUP SIS)',
                'description' => 'The official online portal for students and faculty, providing access to enrollment, grades, class schedules, and other academic transactions. ',
                'url' => 'https://sis8.pup.edu.ph/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP eMabini',
                'description' => 'The official online learning portal of the PUP Open University System, providing distance and nontraditional learners access to virtual courses, tutorials, and educational resources.',
                'url' => 'https://emabini.pup.edu.ph/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
             [
                'title' => 'Online Document Request System (ODRS)',
                'description' => 'Allows students and alumni to request official documents, such as transcripts and certifications, from various PUP offices.',
                'url' => 'https://odrs.pup.edu.ph/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
             [
                'title' => 'PUP Main Campus eLearning Management System',
                'description' => 'The official LMS of PUP Main Campus where students access course materials, submit assignments, take quizzes, and interact with professors online.',
                'url' => 'https://lms.pup.edu.ph/maincampus/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Technology Business Incubator (TBI) Pylon',
                'description' => 'The official incubator of PUP that supports student and faculty startups by providing mentorship, workspace, funding guidance, and resources to turn innovative ideas into viable businesses. ',
                'url' => 'https://www.puptbi.site/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Student Council Commission on Student Organizations and Accreditation (PUP SC COSOA) Portal',
                'description' => 'The official website of the PUP SC COSOA, providing information on recognized student organizations, accreditation and revalidation processes, and resources for student leaders.',
                'url' => 'https://anrcosmo.com/',
                'type' => 'website',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            //Official Facebook Pages
            [
                'title' => 'Polytechnic University of the Philippines (Official Facebook Page)',
                'description' => 'The official Facebook page of the university, serving as the main channel for announcements and campus news.',
                'url' => 'https://web.facebook.com/ThePUPOfficial?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Scholarship',
                'description' => 'Provides access to educational opportunities and shares updates on scholarship programs, grants, and student financial support.',
                'url' => 'https://web.facebook.com/PUPSFAS?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Career Center',
                'description' => 'Assists students and alumni in finding internships or employment and developing career skills.',
                'url' => 'https://www.facebook.com/pupcareer',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Office of Guidance and Counseling',
                'description' => 'Provides students with updates, mental health resources, counseling programs, and information on guidance services available across the university.',
                'url' => 'https://web.facebook.com/PUPGuidanceOfficial?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Open University System',
                'description' => 'Provides updates, announcements, and information about distance learning programs, online courses, and resources for non-traditional students.',
                'url' => 'https://web.facebook.com/pupous.1990?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP International Relations Office',
                'description' => 'Shares updates on student exchange programs, international partnerships, global initiatives, and events.',
                'url' => 'https://web.facebook.com/PUPOFIA?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
             [
                'title' => 'PUP Sports Development Program Office (SDPO)',
                'description' => "The official page of PUP’s Sports Development Program Office, sharing updates on varsity teams, tryouts, athletic events, and sports-related announcements.",
                'url' => 'https://www.facebook.com/pupsdpo',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP PYLON TBI',
                'description' => 'The official Facebook page of PUP Technology Business Incubator where they post announcements about events, opportunities, and even about the free co-working space. They offer a study hub for students located at the 4th Floor, NALRC Building, PUP – Sta. Mesa. Open Monday to Friday with free WiFi available. Slide into their DMs for reservations or inquiries.',
                'url' => 'https://www.facebook.com/DOSTPUPPYLONTBI',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Office of the Student Regent',
                'description' => 'Updates on student representation at the university board level, initiatives, and announcements directly from the student regent.',
                'url' => 'https://web.facebook.com/thepuposr?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Sentral na Konseho ng Mag-aaral (SKM)',
                'description' => 'The main platform for the student council of PUP Main Campus, sharing programs, governance activities, and campus events.',
                'url' => 'https://web.facebook.com/thepupskm?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'The Catalyst',
                'description' => 'The official student publication of the university, providing news, feature stories, campus updates, and highlights of student-led initiatives.',
                'url' => 'https://web.facebook.com/pup.thecatalyst?_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Campus Journalists',
                'description' => 'An autonomous student publication of PUP Sta. Mesa.',
                'url' => 'https://www.facebook.com/pupcjs',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'Gabay Sinta',
                'description' => 'The official PUPCET information drive providing aspiring Iskolars ng Bayan with updates, announcements, and guidance on the PUPCET application and admission process.',
                'url' => 'https://web.facebook.com/profile.php?id=61569174075354&_rdc=10&_rdr',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUPM DOST - SEI Scholars',
                'description' => 'The official DOST-SEI Satellite Office of the Polytechnic University of the Philippines Sta. Mesa',
                'url' => 'https://www.facebook.com/profile.php?id=61584683286009',
                'type' => 'facebook_page',
                'is_official' => true,
                'sort_order' => 1,
                'is_active' => true,
            ],
            //Unofficial Facebook Pages
             [
                'title' => 'PUP Sta. Mesa Freedom Wall',
                'description' => 'A freedom wall-style Facebook Page where PUP students share anonymous thoughts, confessions, rants, memes, and campus experiences, unfiltered and student-driven.',
                'url' => 'https://www.facebook.com/pupfw2.0',
                'type' => 'facebook_page',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
             [
                'title' => 'Kolehiyo Updates',
                'description' => 'The first and biggest network for college and scholarship application updates.',
                'url' => 'https://www.facebook.com/kolehiyoupdates',
                'type' => 'facebook_page',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUPian Lifestyle',
                'description' => 'The First Spirit-wear for PUP by PUPians',
                'url' => 'https://www.facebook.com/pupianlifestyle',
                'type' => 'facebook_page',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'Tanglaw Clothing',
                'description' => 'The trendsetter clothing brand for every PUPian',
                'url' => 'https://www.facebook.com/TanglawClothing19',
                'type' => 'facebook_page',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            // Subreddits
            [
                'title' => 'r/PUPians',
                'description' => 'Reddit community for PUP students and alumni to discuss campus life, academics, experiences, and anything related to Sintang Paaralan.',
                'url' => 'https://www.reddit.com/r/PUPians/',
                'type' => 'subreddit',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'r/SintangPaaralan',
                'description' => 'A subreddit dedicated to conversations about PUP, from student stories and advice to memes, campus issues, and open discussions.',
                'url' => 'https://www.reddit.com/r/SintangPaaralan/',
                'type' => 'subreddit',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'r/BosesNgPUP',
                'description' => 'This is PUPian’s dump! Para mag-chill at mag-share ng anything, thoughts, feels, memes, drama, o kahit anong gusto mo, papakinggan namin yan!',
                'url' => 'https://www.reddit.com/r/BosesNgPUP/',
                'type' => 'subreddit',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            //Facebook Group Communities
            [
                'title' => 'PUP Community (Est. 2021)',
                'description' => 'A Facebook group for general discussions among PUPians about announcements, questions, campus updates, issues, rants, lost and found and student life topics.',
                'url' => 'https://www.facebook.com/groups/1053371471837943',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'Usap-usapan sa PUP',
                'description' => 'An open discussion group where PUPians talk about campus issues, experiences, trends, and everyday university life.',
                'url' => 'https://www.facebook.com/groups/usap.usapan.sa.pup',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'PUP Confession',
                'description' => 'A community group where students anonymously share stories, crushes, rants, and personal experiences within the PUP community.',
                'url' => 'https://www.facebook.com/groups/2487502114746209',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
             [
                'title' => 'PUP Tiangge',
                'description' => 'A buy-and-sell group for PUPians, from school supplies and gadgets to thrifted clothes and small business promos.',
                'url' => 'https://www.facebook.com/groups/972664604923426',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
             [
                'title' => 'PUP Dorm Hunt',
                'description' => 'A space for students looking for dorms, apartments, or bedspaces near PUP, including listings, inquiries, and roommate searches.',
                'url' => 'https://www.facebook.com/groups/239211413448123',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'Dorm Seekers!!! University Belt Manila - PRC Morayta',
                'description' => 'A Facebook group for students seeking dorms/apartments/units.',
                'url' => 'https://www.facebook.com/groups/2037889166511003',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'UPCAT/PUPCET/DOST/ACET/DCAT/USTET/PLMAT/FEUCAT/PNUAT Reviewers/Takers',
                'description' => 'A student-driven Facebook group where exam takers share reviewers, tips, experiences, and updates for major college entrance tests and scholarship exams.',
                'url' => 'https://www.facebook.com/groups/232521194171992',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => 'KOLEHIYO UPDATES: College Admission Preparation',
                'description' => 'A Facebook group for students who are preparing for their college admission journey.',
                'url' => 'https://www.facebook.com/groups/900980571851683',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ],
            [
                'title' => '2026-2027 PUPCET Admission Inquiries Group',
                'description' => 'A Facebook group for students planning to apply to PUP, where you can ask questions, get clarifications, and stay updated on all things PUPCET.',
                'url' => 'https://www.facebook.com/groups/pupcet',
                'type' => 'community',
                'is_official' => false,
                'sort_order' => 1,
                'is_active' => true,
            ]
        ];

        foreach ($links as $link) {
            Link::firstOrCreate(
                ['url' => $link['url']],
                $link
            );
        }
    }
}
